compatibility_date = "2022-05-17"
name = "karma-bot"
workers_dev = true

kv_namespaces = [
  {binding = "KV_KARMA", id = "", preview_id = ""},
]

[vars]
RESPONSE_TYPE = ''
# RESPONSE_TYPE = 'in_channel'